### ISSUE TITLE
Does not list all the fonts that are used

### ISSUE THREAD

**Issue by aziz** [fChristenson/sassy-stats#3] opened 2017-01-16 15:32 UTC

**Comment by fChristenson** [comment] 2017-01-16 20:34
@aziz I looked into the files and there are no font-family refs to TMSans, it is only used inside mixins and as part of maps or as part of a font face declaration.

The issue is not the font the know issue that sassy-stats does not handle scoped props.

Closing this and hopefully it will be solved when sassy-tools can handle reading mixing/func bodies.

**Closed** 2017-01-16 20:34 UTC

**Comment by aziz** [comment] 2017-01-16 20:36
:+1:
